### ISSUE TITLE
Disconnect endpoint with SSO

### ISSUE THREAD

**Issue by raviroyind** [IntuitDeveloper/OAuth2_DotnetCore_MVC5_SampleApp#9]
Does not includes sample of "disconnect" from app store.

**Comment by nimisha84** [comment]
Please use this - https://developer.intuit.com/app/developer/qbo/docs/list-on-the-app-store/app-settings#intuit-non-single-sign-on-settings 
Disconnect URL: This is a placeholder for your app’s Disconnect link.When Disconnect is clicked from Quickbooks company, Intuit will revoke the token internally and Your user lands on this page after the app disconnects from your user’s QuickBooks company. This url should again perform an OpenIdConnect (OAuth2) process as shown for Launch above, by sending scope as only OpenId+Email etc. (Do not send accounting).`Implement the Connect to QuickBooks button </app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#add-the-connect-to-quickbooks-button>`__ and single sign-on on this page using API related scopes like for Accounting, Payments etc so that users can reconnect immediately. So, through this link, when a customer disconnects, Intuit passes your app an OpenID assertion </app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect>__ about the user that just disconnected from your app. You can use that assertion to look up the user and mark them as disconnected or send them a message.
